server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: aimatch-gateway
  profiles:
    include: common
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public
        ephemeral: true
        grpc:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uaa-service
          uri: lb://aimatch-uaa
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=1
        - id: business-service
          uri: lb://aimatch-business
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    org.springframework.cloud.gateway: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: error 